# Generated by Django 5.2.17 on 2026-09-30 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='nom')),
                ('urls', models.TextField(help_text='Une URL par ligne')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], db_index=True, default='pending', max_length=10)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('urls_count', models.PositiveIntegerField(default=0)),
                ('urls_done', models.PositiveIntegerField(default=0)),
                ('urls_failed', models.PositiveIntegerField(default=0)),
                ('items_scraped', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tâche de crawl',
                'verbose_name_plural': 'tâches de crawl',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='crawler_cra_user_id_80c48a_idx')],
            },
        ),
    ]
